enviroment : development

server:
  host: "0.0.0.0"
  port: "8000"
  workers: 4

simulation:
  default_volume: 1.0
  default_cp: 4.18
  default_rho: 1000
  default_k0: 100
  default_ea: 50000
  default_dhr: 60000
  default_ua: 500


pid:
  default_kp: 5.0
  default_ki: 0.2
  default_kd: 1.0
  default_setpoint: 350.0
  default_dt: 1.0

neural_network:
  default_architecture: "hybrid"
  default_hidden_units: 200
  default_lstm_layers: 2
  default_attention_heads: 4
  default_learning_rates: 0.001
  default_epochs: 100
  sequence_window: 10

training:
  n_scenarios: 20
  n_steps_per_scenario: 100
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
